### ISSUE TITLE
Unicode strings not supported ...

### ISSUE THREAD

**Issue by MFeldtmann** [GsDevKit/NeoJSON#5]
... instances of Utf8 and Unicode16 are not supported ... 

Unicode16>>neoJsonOn: neoJSONWriter
	self encodeAsUTF8 neoJsonOn: neoJSONWriter
Utf8>>neoJsonOn: neoJSONWriter
	neoJSONWriter writeUTF8ByteArrayAsString: self
NeoJSONWriter>>writeUTF8ByteArrayAsString: byteArray
	writeStream nextPut: $".
	byteArray do: [ :each |	self encodeCodePoint: each ].
	writeStream nextPut: $"
NeoJSONWriter>>encodeCodePoint: code
	(self doesCodePointNeedEscaping: code)
		ifTrue: [ self escapeChar: code ]
		ifFalse: [ writeStream nextPut: (Character value: code) ]

Some similar extension may be needed for Unicode32 ...

**Comment by MFeldtmann** [comment]
No, this does not make sense to me ... regarding your idea.

If I have 'Mäöü' and I say 

 (NeoJSONWriter toString: 'Mäöü'  asUnicodeString) 

I get "M\u00E4\u00F6\u00FC" (which is ok) and does not need to be converted back to UTF8, because actually it is now simple Unicode7 and therefore plain asciiOnly representation and also a valid UTF8 encoding - BUT not efficient.

If one takes the encoding into account then to encode this back to UTF8 is even more inefficient. 

To summarize: the situation is good for Unciode7-countries, but the rest still gets problems.






In your original report you mention that you'd like to implement have an implementation for Utf8>>neoJsonOn:. A this point I am of the opinion that directly storing UTF-8 encoded Strings as a JSON string field is not correct. OTOH, It would be correct to produce a Unicode string from the Utf8 instance and then store that in a JSON string field which would then be encoded based on the asciiOnly settings and the resulting JSON string would be encoded in UTF-8 (or whatever) in it's entirely.

Does this make sense, to you?

**Comment by dalehenrich** [comment]
On 01/05/2015 06:47 AM, MFeldtmann wrote:
>
> No, this does not make sense to me ... regarding your idea.
>
I'm not quite sure which of "my ideas" do not make sense:)

The bullet points in [this 
comment](https://github.com/GsDevKit/NeoJSON/issues/5#issuecomment-64500636) 
are all based on my understanding of the actual JSON spec.

> If I have 'Mäöü' and I say
>
> (NeoJSONWriter toString: 'Mäöü' asUnicodeString)
>
> I get "M\u00E4\u00F6\u00FC" (which is ok) and does not need to be 
> converted back to UTF8, because actually it is now simple Unicode7 and 
> therefore plain asciiOnly representation and also a valid UTF8 
> encoding - BUT not efficient.
>
The only reason I mention the bit about UTf8 encoding is that the spec 
claims that

 >> JSON text SHALL be encoded in Unicode. The default encoding is UTF-8.

You are correct in pointing out that given the way that strings are 
encoded in JSON, further UTF8 encoding for String fileds is not 
necessary. Perhaps Unicode16 and Unicode32 characters can be used in 
non-character fields? If so, then requiring UTF8 encoding makes sense ...

> If one takes the encoding into account then to encode this back to 
> UTF8 is even more inefficient.
>
> To summarize: the situation is good for Unciode7-countries, but the 
> rest still gets problems.
>
> In your original report you mention that you'd like to implement have 
> an implementation for Utf8>>neoJsonOn:. A this point I am of the 
> opinion that directly storing UTF-8 encoded Strings as a JSON string 
> field is not correct.
>
I agree. My original comment was made before I had gotten more familiar 
with the JSON spec ... after becoming familiar with the spec for 
encoding JSON strings, I also realized that I was incorrectly encoding 
strings for [STON](https://github.com/GsDevKit/ston/issues/6)
>
> OTOH, It would be correct to produce a Unicode string from the Utf8 
> instance and then store that in a JSON string field which would then 
> be encoded based on the asciiOnly settings and the resulting JSON 
> string would be encoded in UTF-8 (or whatever) in it's entirely.
>
> Does this make sense, to you?
>
It's not quite clear what you are saying here.

I assume that since you submitted Issue #6, that you are implying that 
by using asciiOnly, you are expecting NeoJSON to not encode characters 
at all in asciiOnly mode?

I believe that that interpretation is incorrect as there are explicit 
tests for asciiOnly where the expected results include encoding for code 
points > 126 ...

Perhaps we should add a unicodeMode, where no character encoding is done 
we rely on the UTF8 encodoing of the entire packet to convert everything 
to Unicode7?

Dale

**Comment by dalehenrich** [comment]
reopen until this recent discussion is completed

**Comment by MFeldtmann** [comment]
Ok, I have to think about that again:

a) asciiOnly = true (default = false) means, that the resulting JSON text is ASCII only or better: Unicode7 and inefficient. The resulting String based stream contains instances of Characters - actually suitable for instances of Unicode7 class. My opinion in my previous posting about asciiOnly was false ...

b) asciiOnly = false means, that the characters > 126 are not escaped but put without conversion to the output stream. The resulting String based stream is used as a container - an encoding is not known or better: the encoding may change according to the strings printed to the stream. 

Even though a) is the cleaner solution everybody uses b). Therefore if I have an Utf8 instance I would like to be able to print this directly to that stream (assuming, that the resulting stream is UTF8 based) - without conversion to unicode. Therefore I added methods for instances of Utf8 and Unicode16.

b) is overall an ugly implementation. In my opinion the NeoJSONWriter and Reader class should work on streams knowing their encoding and conversion is done on this encoding-class (not by NeoJSONWriter). In such a case I would NeoJSONWriter ask for an UTF8 encoding stream (or Unicode16) and then do the work on that stream. That's a much better model - but I think, that Squeak/Pharo compatibility is more important.

Leave the code as it is. I'll patch it here and must have a stable code base ...

**Comment by dalehenrich** [comment]
It is worth noting that in 3.2+ GsDevKit  when CharacterCollection instances are written to a Stream, the encoding is coerced to Unicode... In Pharo, I think that the Stream is coearced to become WideString ... so different String types can be written to a Stream without losing information ...

**Comment by MFeldtmann** [comment]
Actually I do not understand (or simply do not see it), what this means or my examples (I tried out) did not work (under 3.2.3). Do have an example ?

**Comment by dalehenrich** [comment]
The examples that I provided above were done using 3.2.2. What examples did you try and what "did not work?"

Did you not get the same results that [I showed in the example above](https://github.com/GsDevKit/NeoJSON/issues/5#issuecomment-68776771)? That example was produced running against 3.2.2 and the latest commit on the NeoJSON branch (5f6dc72)...

**Comment by dalehenrich** [comment]
If you want we could try chatting over in the [GsDevKit chat room on gitter](https://gitter.im/GsDevKit/chat) ... it's something new and I have not publicized the chat room, but if it turns out to be useful I will make a general announcement...

**Comment by MFeldtmann** [comment]
>Where the Strings themselves are encoded in UTF8 before being added to JSON, but I would be concerned that non-NeoJSON clients would not be able decode those Strings properly, since I believe that the JSON standard insists that String fields use the Character encoding sceme...

I see, where this asciFlag= true comes from: Python also uses this one. And your question regarding UTF8 code within string fields: 

http://stackoverflow.com/questions/12309269/write-json-data-to-file-in-python/14870531#14870531

**Comment by MFeldtmann** [comment]
Another question and its answer:

http://stackoverflow.com/questions/583562/json-character-encoding-is-utf-8-well-supported-by-browsers-or-should-i-use-nu

**Comment by dalehenrich** [comment]
Very good, then `(NeoJSONWriter toString: str1) encodeAsUTF8` is very likely to be compatible with most clients ... talk to @rjsargent, we surmised that the character encoding pre-dated ubiquitous utf8 support ...

**Comment by MFeldtmann** [comment]
The asciiFlag is useful for these transport ways, where 7bit is still the way to go - though I have not met such a transport way in my practical life. Other that this: I still think, that UTF8/UTF16 is also used for the strings itself.

**Comment by MFeldtmann** [comment]
That brings us back to the point, where ones want to add unicodestrings and utf8 strings directly to the JSON text again ... via my methods ...

**Comment by MFeldtmann** [comment]
And another stackoverflow interpretation

http://stackoverflow.com/questions/11641983/encoding-json-in-utf-16-or-utf-32?rq=1

**Comment by dalehenrich** [comment]
If I am not mistaken, there is no need to do anything special to include unicode strings in NeoJSON, as the following works correctly:

```Smalltalk
  | str1 json str2 |
  str1 := #[240 163 142 143] decodeFromUTF8.
  json := (NeoJSONWriter toString: str1) encodeAsUTF8.	"on server"
  str2 := NeoJSONReader fromString: json decodeFromUTF8	"on client"
```

I still need to see a concrete example of why need to do anything special other the above. 

I do not have a good idea of what "via my methods" means, since NeoJSON already lets you add "unicode strings directly to JSON text".

A concrete example, please?

**Comment by dalehenrich** [comment]
I suppose if you are not proposing to add these "new methods" to NeoJSON it doesn't actually matter what your use case is, but I still am curious:)
